import axiosInstance from "./axiosInstance";

import type{VehicleInfo,
  AppointmentData,
  GetAllAppointmentsParams,
  Appointment}
  from "../types/appointment";
// Book a new appointment - appointmentId will be auto-generated by backend
export const bookAppointment = async (appointmentData: AppointmentData) => {
  try {
    // Remove any appointmentId if present (shouldn't be in AppointmentData interface)
    const { appointmentId, ...dataToSend } = appointmentData as any;
    
    const response = await axiosInstance.post("/appointments", dataToSend);
    return response.data;
  } catch (error) {
    console.error('Error booking appointment:', error);
    throw error;
  }
};

// Get all appointments for a user
export const getAppointmentsByUser = async (userId: string) => {
  try {
    const response = await axiosInstance.get(`/appointments/user/${userId}`);
    return response.data; // Return the full response to handle in the component
  } catch (error: any) {
    console.error('Error in getAppointmentsByUser:', error);
    
    // Handle 404 specifically - means no appointments found for user
    if (error.response?.status === 404) {
      return {
        success: true,
        appointments: [],
        message: error.response.data?.message || 'No appointments found for this user'
      };
    }
    
    // For other errors, throw the error
    throw error;
  }
};

// Get single appointment by appointmentId (not MongoDB _id)
export const getAppointmentById = async (appointmentId: string | number) => {
  try {
    // Encode the appointmentId in case it has special characters (like AP-1001)
    const encodedId = encodeURIComponent(appointmentId.toString());
    const response = await axiosInstance.get(`/appointments/appointment/${encodedId}`);
    return response.data;
  } catch (error) {
    console.error('Error getting appointment:', error);
    throw error;
  }
};

// Cancel appointment by appointmentId
export const cancelAppointment = async (appointmentId: string | number, reason?: string) => {
  try {
    console.log('Attempting to cancel appointment:', appointmentId);
    
    // Encode the appointmentId
    const encodedId = encodeURIComponent(appointmentId.toString());
    
    // Use the cancel endpoint with appointmentId
    const response = await axiosInstance.patch(
      `/appointments/appointment/cancel/${encodedId}`, // Updated endpoint
      { 
        cancellationReason: reason || 'Cancelled by user'
      }
    );
    
    console.log('Cancel response:', response.data);
    return response.data;
    
  } catch (error) {
    console.error('Full error details:', error);
    console.error('Error config:', (error as any).config);
    throw error;
  }
};

// Update appointment by appointmentId (e.g., reschedule)
export const updateAppointment = async (appointmentId: string | number, updates: Partial<AppointmentData>) => {
  try {
    const encodedId = encodeURIComponent(appointmentId.toString());
    const response = await axiosInstance.put(`/appointments/appointment/${encodedId}`, updates);
    return response.data;
  } catch (error) {
    console.error('Error updating appointment:', error);
    throw error;
  }
};

// Get all appointments (admin function)
export const getAllAppointments = async (params?: GetAllAppointmentsParams) => {
  try {
    const response = await axiosInstance.get("/appointments/appointment", {
      params: {
        page: params?.page || 1,
        limit: params?.limit || 20,
        serviceType: params?.serviceType,
        status: params?.status,
        date: params?.date,
        sortBy: params?.sortBy || 'createdAt',
        sortOrder: params?.sortOrder || 'desc'
      }
    });
    return response.data;
  } catch (error: any) {
    console.error('Error fetching all appointments:', error);
    throw error; // Return the original error to maintain the structure
  }
};

// To update status of an appointment by appointmentId
export const updateAppointmentStatus = async (appointmentId: string | number, status: string, adminNotes?: string) => {
  try {
    const encodedId = encodeURIComponent(appointmentId.toString());
    const response = await axiosInstance.patch(`/appointments/appointment/${encodedId}/status`, {
      status: status,
      adminNotes: adminNotes
    });
    return response.data;
  } catch (error: any) {
    console.error('Error updating appointment status:', error);
    
    // Handle specific error codes
    if (error.response?.data?.code === 'APPOINTMENT_CANCELLED') {
      throw {
        success: false,
        message: 'This appointment was cancelled and cannot be modified',
        error: error.message
      };
    }
    
    if (error.response?.data?.code === 'APPOINTMENT_ALREADY_CONFIRMED') {
      throw {
        success: false,
        message: 'Appointment is already confirmed',
        error: error.message
      };
    }
    
    throw {
      success: false,
      message: error.response?.data?.message || 'Failed to update appointment status',
      error: error.message
    };
  }
};

// Additional helper function if you need to search appointments
export const searchAppointments = async (searchTerm: string) => {
  try {
    const response = await axiosInstance.get(`/appointments/search?q=${encodeURIComponent(searchTerm)}`);
    return response.data;
  } catch (error) {
    console.error('Error searching appointments:', error);
    throw error;
  }
};

// Update bill items for an appointment
export const updateBillItems = async (appointmentId: string | number, billItems: Array<{
  itemName: string;
  itemPrice: number;
  serviceCharge: number;
}>) => {
  try {
    const encodedId = encodeURIComponent(appointmentId.toString());
    const response = await axiosInstance.put(`/appointments/appointment/${encodedId}/bill`, {
      billItems
    });
    return response.data;
  } catch (error: any) {
    console.error('Error updating bill items:', error);
    throw {
      success: false,
      message: error.response?.data?.message || 'Failed to update bill items',
      error: error.message
    };
  }
};